# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Ingredient.create(title: 'Бренди', category: 'Алкогольные напитки', protein: 0, fat: 0, sugar: 1, calories: 225)
Ingredient.create(title: 'Вермут', category: 'Алкогольные напитки', protein: 0, fat: 0, sugar: 15.9, calories: 155)
Ingredient.create(title: 'Вино сухое', category: 'Алкогольные напитки', protein: 0, fat: 0, sugar: 0, calories: 66)
Ingredient.create(title: 'Вино полусухое', category: 'Алкогольные напитки', protein: 0.3, fat: 0, sugar: 2.5, calories: 78)
Ingredient.create(title: 'Вино десертное', category: 'Алкогольные напитки', protein: 0.5, fat: 0, sugar: 20, calories: 175)
Ingredient.create(title: 'Вино полусладкое', category: 'Алкогольные напитки', protein: 0.2, fat: 0, sugar: 5, calories: 88)
Ingredient.create(title: 'Вино столовое', category: 'Алкогольные напитки', protein: 0.2, fat: 0, sugar: 0.2, calories: 67)
Ingredient.create(title: 'Виски', category: 'Алкогольные напитки', protein: 0, fat: 0, sugar: 0, calories: 222)
Ingredient.create(title: 'Водка', category: 'Алкогольные напитки', protein: 0, fat: 0, sugar: 0.1, calories: 234)
Ingredient.create(title: 'Джин', category: 'Алкогольные напитки', protein: 0, fat: 0, sugar: 0, calories: 223)
Ingredient.create(title: 'Коньяк', category: 'Алкогольные напитки', protein: 0, fat: 0, sugar: 0.1, calories: 240)
Ingredient.create(title: 'Ликер', category: 'Алкогольные напитки', protein: 0, fat: 0, sugar: 53, calories: 344)
Ingredient.create(title: 'Пиво 3.0%', category: 'Алкогольные напитки', protein: 0.6, fat: 0, sugar: 3.5, calories: 37)
Ingredient.create(title: 'Пиво 4.5%', category: 'Алкогольные напитки', protein: 0.8, fat: 0, sugar: 4.5, calories: 45)
Ingredient.create(title: 'Пиво темное', category: 'Алкогольные напитки', protein: 0.2, fat: 0, sugar: 4, calories: 39)
Ingredient.create(title: 'Портвейн', category: 'Алкогольные напитки', protein: 0, fat: 0, sugar: 13.8, calories: 167)
Ingredient.create(title: 'Ром', category: 'Алкогольные напитки', protein: 0, fat: 0, sugar: 0, calories: 217)
Ingredient.create(title: 'Шампанское', category: 'Алкогольные напитки', protein: 0.3, fat: 0, sugar: 5.2, calories: 88)
Ingredient.create(title: 'Абрикосовый сок', category: 'Безалкогольные напитки', protein: 0.9, fat: 0.2, sugar: 9.2, calories: 39)
Ingredient.create(title: 'Ананасовый сок', category: 'Безалкогольные напитки', protein: 0.2, fat: 0.2, sugar: 11.4, calories: 48)
Ingredient.create(title: 'Апельсиновый сок', category: 'Безалкогольные напитки', protein: 0.9, fat: 0.1, sugar: 8.4, calories: 36)
Ingredient.create(title: 'Виноградный сок', category: 'Безалкогольные напитки', protein: 0.3, fat: 0, sugar: 14.5, calories: 56)
Ingredient.create(title: 'Вишневый сок', category: 'Безалкогольные напитки', protein: 0.5, fat: 0, sugar: 10.6, calories: 49)
Ingredient.create(title: 'Гранатовый сок', category: 'Безалкогольные напитки', protein: 0.2, fat: 0, sugar: 14, calories: 58)
Ingredient.create(title: 'Какао на молоке', category: 'Безалкогольные напитки', protein: 24, fat: 17, sugar: 33.1, calories: 377)
Ingredient.create(title: 'Квас хлебный', category: 'Безалкогольные напитки', protein: 0.2, fat: 0, sugar: 5, calories: 26)
Ingredient.create(title: 'Кола', category: 'Безалкогольные напитки', protein: 0, fat: 0, sugar: 10, calories: 40)
Ingredient.create(title: 'Кофе с молоком', category: 'Безалкогольные напитки', protein: 0.8, fat: 1, sugar: 11, calories: 56)
Ingredient.create(title: 'Лимонад', category: 'Безалкогольные напитки', protein: 0, fat: 0, sugar: 6.1, calories: 24)
Ingredient.create(title: 'Лимонный сок', category: 'Безалкогольные напитки', protein: 1, fat: 0.1, sugar: 3.2, calories: 18)
Ingredient.create(title: 'Морковный сок', category: 'Безалкогольные напитки', protein: 1, fat: 0.1, sugar: 6.5, calories: 31)
Ingredient.create(title: 'Персиковый сок', category: 'Безалкогольные напитки', protein: 0.8, fat: 0.1, sugar: 9.1, calories: 37)
Ingredient.create(title: 'Пиво безалкогольное', category: 'Безалкогольные напитки', protein: 0, fat: 0, sugar: 4.1, calories: 22)
Ingredient.create(title: 'Зеленый чай', category: 'Безалкогольные напитки', protein: 0, fat: 0, sugar: 0, calories: 0)
Ingredient.create(title: 'Черный чай без сахара', category: 'Безалкогольные напитки', protein: 0, fat: 0, sugar: 0, calories: 0)
Ingredient.create(title: 'Черный чай с лимоном и сахаром', category: 'Безалкогольные напитки', protein: 0.8, fat: 0.7, sugar: 8.3, calories: 41)
Ingredient.create(title: 'Черный чай со сгущенным молоком', category: 'Безалкогольные напитки', protein: 2.4, fat: 2.9, sugar: 19.1, calories: 112)
Ingredient.create(title: 'Энергетический напиток', category: 'Безалкогольные напитки', protein: 0, fat: 0, sugar: 11.4, calories: 47)
Ingredient.create(title: 'Яблочный сок', category: 'Безалкогольные напитки', protein: 0.5, fat: 0.4, sugar: 9.7, calories: 42)
Ingredient.create(title: 'Белые свежие', category: 'Грибы', protein: 3.3, fat: 1.5, sugar: 2.4, calories: 32)
Ingredient.create(title: 'Белые сушеные', category: 'Грибы', protein: 23.8, fat: 6.8, sugar: 30.2, calories: 277)
Ingredient.create(title: 'Вешенки свежие', category: 'Грибы', protein: 2.5, fat: 0.5, sugar: 6.2, calories: 34)
Ingredient.create(title: 'Лисички свежие', category: 'Грибы', protein: 1.5, fat: 1, sugar: 2.4, calories: 22)
Ingredient.create(title: 'Лисички сушеные', category: 'Грибы', protein: 22, fat: 7.2, sugar: 25.4, calories: 268)
Ingredient.create(title: 'Маслята свежие', category: 'Грибы', protein: 2.5, fat: 0.7, sugar: 1.5, calories: 12)
Ingredient.create(title: 'Опята свежие', category: 'Грибы', protein: 2.4, fat: 1, sugar: 2.5, calories: 25)
Ingredient.create(title: 'Подберезовики свежие', category: 'Грибы', protein: 2.1, fat: 1.2, sugar: 3.4, calories: 30)
Ingredient.create(title: 'Подберезовики сушеные', category: 'Грибы', protein: 23.3, fat: 9.5, sugar: 14.4, calories: 231)
Ingredient.create(title: 'Подосиновики свежие', category: 'Грибы', protein: 3.3, fat: 0.4, sugar: 3.5, calories: 31)
Ingredient.create(title: 'Подосиновики сушеные', category: 'Грибы', protein: 35.2, fat: 5.4, sugar: 33, calories: 325)
Ingredient.create(title: 'Рыжики свежие', category: 'Грибы', protein: 1.9, fat: 0.7, sugar: 2.3, calories: 16)
Ingredient.create(title: 'Сыроежки свежие', category: 'Грибы', protein: 1.6, fat: 0.8, sugar: 1.7, calories: 15)
Ingredient.create(title: 'Шампиньоны свежие', category: 'Грибы', protein: 4.3, fat: 0.9, sugar: 1.4, calories: 29)
Ingredient.create(title: 'Икра кеты зернистая', category: 'Икра', protein: 31.6, fat: 13.7, sugar: 0, calories: 250)
Ingredient.create(title: 'Икра лещевая пробойная', category: 'Икра', protein: 24.6, fat: 4.9, sugar: 0, calories: 144)
Ingredient.create(title: 'Икра минтая пробойная', category: 'Икра', protein: 28.3, fat: 1.8, sugar: 0, calories: 127)
Ingredient.create(title: 'Икра осетровая зернистая', category: 'Икра', protein: 28.3, fat: 9.6, sugar: 0, calories: 201)
Ingredient.create(title: 'Икра осетровая пробойная', category: 'Икра', protein: 36.3, fat: 10.1, sugar: 0, calories: 235)
Ingredient.create(title: 'Гречневая каша', category: 'Каши', protein: 4.5, fat: 1.6, sugar: 27.4, calories: 137)
Ingredient.create(title: 'Кукурузные хлопья', category: 'Каши', protein: 6.5, fat: 2.9, sugar: 83.8, calories: 372)
Ingredient.create(title: 'Манная каша', category: 'Каши', protein: 2.5, fat: 0.3, sugar: 16.4, calories: 77)
Ingredient.create(title: 'Овсяная каша', category: 'Каши', protein: 3.2, fat: 1.8, sugar: 15.4, calories: 93)
Ingredient.create(title: 'Овсяные хлопья', category: 'Каши', protein: 11.9, fat: 7.5, sugar: 69.1, calories: 358)
Ingredient.create(title: 'Перловая каша', category: 'Каши', protein: 3.2, fat: 0.5, sugar: 22.7, calories: 102)
Ingredient.create(title: 'Пшенная каша', category: 'Каши', protein: 3, fat: 0.8, sugar: 17.2, calories: 92)
Ingredient.create(title: 'Рисовая каша', category: 'Каши', protein: 1.5, fat: 0.2, sugar: 17.3, calories: 79)
Ingredient.create(title: 'Ячневая каша', category: 'Каши', protein: 1.4, fat: 0.3, sugar: 18.7, calories: 84)
Ingredient.create(title: 'Ячневые хлопья', category: 'Каши', protein: 9.1, fat: 3.2, sugar: 79.7, calories: 345)
Ingredient.create(title: 'Колбаса вареная Докторская', category: 'Колбаса и колбасные изделия', protein: 13.4, fat: 22.9, sugar: 0, calories: 257)
Ingredient.create(title: 'Колбаса вареная Любительская', category: 'Колбаса и колбасные изделия', protein: 12.5, fat: 28.3, sugar: 0, calories: 311)
Ingredient.create(title: 'Колбаса вареная Молочная', category: 'Колбаса и колбасные изделия', protein: 11.1, fat: 22.5, sugar: 0, calories: 243)
Ingredient.create(title: 'Колбаса полукопченая Любительская', category: 'Колбаса и колбасные изделия', protein: 17.6, fat: 39.1, sugar: 0, calories: 428)
Ingredient.create(title: 'Колбаса полукопченая Московская', category: 'Колбаса и колбасные изделия', protein: 19.1, fat: 36.1, sugar: 0, calories: 402)
Ingredient.create(title: 'Колбаса полукопченая Сервелат', category: 'Колбаса и колбасные изделия', protein: 16.1, fat: 40.2, sugar: 0, calories: 423)
Ingredient.create(title: 'Колбаса сырокопченая Любительская', category: 'Колбаса и колбасные изделия', protein: 20.6, fat: 47.8, sugar: 0, calories: 511)
Ingredient.create(title: 'Колбаса сырокопченая Московская', category: 'Колбаса и колбасные изделия', protein: 24.3, fat: 41.6, sugar: 0, calories: 476)
Ingredient.create(title: 'Колбаса сырокопченая Сервелат', category: 'Колбаса и колбасные изделия', protein: 24.1, fat: 40.2, sugar: 0, calories: 453)
Ingredient.create(title: 'Колбаски охотничьи', category: 'Колбаса и колбасные изделия', protein: 27.1, fat: 24.6, sugar: 0, calories: 325)
Ingredient.create(title: 'Кровянка', category: 'Колбаса и колбасные изделия', protein: 10.6, fat: 17.8, sugar: 14.5, calories: 261)
Ingredient.create(title: 'Салями', category: 'Колбаса и колбасные изделия', protein: 21.3, fat: 53.6, sugar: 1.1, calories: 576)
Ingredient.create(title: 'Сардельки Говяжьи', category: 'Колбаса и колбасные изделия', protein: 11.1, fat: 18.2, sugar: 1.6, calories: 215)
Ingredient.create(title: 'Сардельки Свиные', category: 'Колбаса и колбасные изделия', protein: 10.1, fat: 31.8, sugar: 1.7, calories: 330)
Ingredient.create(title: 'Сосиски Говяжьи', category: 'Колбаса и колбасные изделия', protein: 10.3, fat: 20.3, sugar: 0.9, calories: 229)
Ingredient.create(title: 'Сосиски Куриные', category: 'Колбаса и колбасные изделия', protein: 10.6, fat: 22.1, sugar: 3.3, calories: 242)
Ingredient.create(title: 'Сосиски Любительские', category: 'Колбаса и колбасные изделия', protein: 9.8, fat: 30.1, sugar: 0.4, calories: 318)
Ingredient.create(title: 'Сосиски Молочные', category: 'Колбаса и колбасные изделия', protein: 11.3, fat: 23.9, sugar: 1.1, calories: 260)
Ingredient.create(title: 'Сосиски Свиные', category: 'Колбаса и колбасные изделия', protein: 9.2, fat: 23.2, sugar: 4.5, calories: 284)
Ingredient.create(title: 'Жир куриный', category: 'Масло, маргарин, жиры', protein: 0, fat: 99.7, sugar: 0, calories: 896)
Ingredient.create(title: 'Жир свиной топленый', category: 'Масло, маргарин, жиры', protein: 0, fat: 99.5, sugar: 0, calories: 882)
Ingredient.create(title: 'Маргарин сливочный', category: 'Масло, маргарин, жиры', protein: 0.5, fat: 82.3, sugar: 0, calories: 746)
Ingredient.create(title: 'Маргарин столовый молочный', category: 'Масло, маргарин, жиры', protein: 0.5, fat: 82, sugar: 0.9, calories: 744)
Ingredient.create(title: 'Майонез 67%', category: 'Масло, маргарин, жиры', protein: 3.3, fat: 67, sugar: 2.4, calories: 624)
Ingredient.create(title: 'Масло льняное', category: 'Масло, маргарин, жиры', protein: 0, fat: 99.8, sugar: 0, calories: 898)
Ingredient.create(title: 'Масло оливковое', category: 'Масло, маргарин, жиры', protein: 0, fat: 99.8, sugar: 0, calories: 898)
Ingredient.create(title: 'Масло подсолнечное', category: 'Масло, маргарин, жиры', protein: 0, fat: 99.9, sugar: 0, calories: 899)
Ingredient.create(title: 'Масло сливочное 82.5%', category: 'Масло, маргарин, жиры', protein: 0.5, fat: 82.5, sugar: 1, calories: 747)
Ingredient.create(title: 'Масло топленое', category: 'Масло, маргарин, жиры', protein: 0.4, fat: 98.1, sugar: 0.5, calories: 885)
Ingredient.create(title: 'Йогурт 1.5%', category: 'Молочные продукты', protein: 4.3, fat: 1.5, sugar: 8.4, calories: 65)
Ingredient.create(title: 'Йогурт 3.2%', category: 'Молочные продукты', protein: 5, fat: 3.2, sugar: 8.9, calories: 87)
Ingredient.create(title: 'Кефир 0%', category: 'Молочные продукты', protein: 2.8, fat: 0, sugar: 3.8, calories: 29)
Ingredient.create(title: 'Кефир 1%', category: 'Молочные продукты', protein: 2.8, fat: 1, sugar: 4.0, calories: 37)
Ingredient.create(title: 'Кефир 2.5%', category: 'Молочные продукты', protein: 3, fat: 2.5, sugar: 4.0, calories: 51)
Ingredient.create(title: 'Кефир 3.2%', category: 'Молочные продукты', protein: 3.2, fat: 3.2, sugar: 4.1, calories: 57)
Ingredient.create(title: 'Молоко 0%', category: 'Молочные продукты', protein: 2.8, fat: 0, sugar: 4.6, calories: 34)
Ingredient.create(title: 'Молоко 1%', category: 'Молочные продукты', protein: 2.8, fat: 1, sugar: 4.6, calories: 43)
Ingredient.create(title: 'Молоко 2.5%', category: 'Молочные продукты', protein: 2.8, fat: 2.5, sugar: 4.6, calories: 53)
Ingredient.create(title: 'Молоко 3.2%', category: 'Молочные продукты', protein: 2.8, fat: 3.2, sugar: 4.6, calories: 58)
Ingredient.create(title: 'Молоко козье сырое', category: 'Молочные продукты', protein: 3.1, fat: 4.2, sugar: 4.7, calories: 71)
Ingredient.create(title: 'Молоко коровье сырое', category: 'Молочные продукты', protein: 3.2, fat: 3.6, sugar: 4.7, calories: 63)
Ingredient.create(title: 'Молоко обезжиренное', category: 'Молочные продукты', protein: 2.1, fat: 0.1, sugar: 4.5, calories: 30)
Ingredient.create(title: 'Молоко сухое цельное', category: 'Молочные продукты', protein: 25.2, fat: 25, sugar: 39.6, calories: 477)
Ingredient.create(title: 'Молоко сгущенное', category: 'Молочные продукты', protein: 7.3, fat: 7.7, sugar: 9.7, calories: 139)
Ingredient.create(title: 'Простокваша 3.2%', category: 'Молочные продукты', protein: 2.9, fat: 3.2, sugar: 4.0, calories: 57)
Ingredient.create(title: 'Ряженка 2.5%', category: 'Молочные продукты', protein: 2.9, fat: 2.5, sugar: 4.1, calories: 53)
Ingredient.create(title: 'Ряженка 4.0%', category: 'Молочные продукты', protein: 2.9, fat: 4, sugar: 4.1, calories: 68)
Ingredient.create(title: 'Сливки 10%', category: 'Молочные продукты', protein: 2.8, fat: 10, sugar: 4.1, calories: 121)
Ingredient.create(title: 'Сливки 20%', category: 'Молочные продукты', protein: 2.8, fat: 20, sugar: 3.9, calories: 209)
Ingredient.create(title: 'Сметана 10%', category: 'Молочные продукты', protein: 3, fat: 10, sugar: 2.9, calories: 118)
Ingredient.create(title: 'Сметана 15%', category: 'Молочные продукты', protein: 3, fat: 15, sugar: 2.9, calories: 163)
Ingredient.create(title: 'Сметана 20%', category: 'Молочные продукты', protein: 3, fat: 20, sugar: 2.9, calories: 208)
Ingredient.create(title: 'Сырки из творожной массы', category: 'Молочные продукты', protein: 7.3, fat: 23, sugar: 27.6, calories: 344)
Ingredient.create(title: 'Сыр голландский', category: 'Молочные продукты', protein: 26.4, fat: 26.5, sugar: 0, calories: 352)
Ingredient.create(title: 'Сыр пошехонский', category: 'Молочные продукты', protein: 26.4, fat: 26.3, sugar: 0, calories: 348)
Ingredient.create(title: 'Сыр российский', category: 'Молочные продукты', protein: 24.1, fat: 29.8, sugar: 0.4, calories: 366)
Ingredient.create(title: 'Сыр сулугуни', category: 'Молочные продукты', protein: 20, fat: 24.2, sugar: 0, calories: 293)
Ingredient.create(title: 'Творог жирный', category: 'Молочные продукты', protein: 14, fat: 18, sugar: 1.9, calories: 236)
Ingredient.create(title: 'Творог нежирный', category: 'Молочные продукты', protein: 18.2, fat: 0.6, sugar: 1.8, calories: 89)
Ingredient.create(title: 'Творог полужирный', category: 'Молочные продукты', protein: 16.5, fat: 9, sugar: 1.9, calories: 156)
Ingredient.create(title: 'Баранина', category: 'Мясо, птица', protein: 16.2, fat: 15.3, sugar: 0, calories: 201)
Ingredient.create(title: 'Бараньи Почки', category: 'Мясо, птица', protein: 13.4, fat: 2.6, sugar: 0, calories: 78)
Ingredient.create(title: 'Баранья Печень', category: 'Мясо, птица', protein: 18.9, fat: 2.8, sugar: 0, calories: 102)
Ingredient.create(title: 'Баранье Сердце', category: 'Мясо, птица', protein: 13.6, fat: 2.7, sugar: 0, calories: 85)
Ingredient.create(title: 'Говядина', category: 'Мясо, птица', protein: 18.7, fat: 12.6, sugar: 0, calories: 191)
Ingredient.create(title: 'Говяжьи Мозги', category: 'Мясо, птица', protein: 9.3, fat: 9.6, sugar: 0, calories: 126)
Ingredient.create(title: 'Говяжья Печень', category: 'Мясо, птица', protein: 17.6, fat: 3.2, sugar: 0, calories: 100)
Ingredient.create(title: 'Говяжьи Почки', category: 'Мясо, птица', protein: 12.4, fat: 1.9, sugar: 0, calories: 67)
Ingredient.create(title: 'Говяжье Вымя', category: 'Мясо, птица', protein: 12.1, fat: 13.8, sugar: 0, calories: 176)
Ingredient.create(title: 'Говяжье Сердце', category: 'Мясо, птица', protein: 15.2, fat: 3.1, sugar: 0, calories: 89)
Ingredient.create(title: 'Говяжий Язык', category: 'Мясо, птица', protein: 13.4, fat: 12.1, sugar: 0, calories: 160)
Ingredient.create(title: 'Конина', category: 'Мясо, птица', protein: 20.3, fat: 7.1, sugar: 0, calories: 149)
Ingredient.create(title: 'Кролик', category: 'Мясо, птица', protein: 20.6, fat: 12.8, sugar: 0, calories: 197)
Ingredient.create(title: 'Свинина нежирная', category: 'Мясо, птица', protein: 16.3, fat: 27.9, sugar: 0, calories: 318)
Ingredient.create(title: 'Свинина жирная', category: 'Мясо, птица', protein: 11.6, fat: 49.1, sugar: 0, calories: 484)
Ingredient.create(title: 'Свиные почки', category: 'Мясо, птица', protein: 13.2, fat: 3.2, sugar: 0, calories: 84)
Ingredient.create(title: 'Свиная печень', category: 'Мясо, птица', protein: 18.6, fat: 3.5, sugar: 0, calories: 105)
Ingredient.create(title: 'Свиное сердце', category: 'Мясо, птица', protein: 15.2, fat: 3.1, sugar: 0, calories: 87)
Ingredient.create(title: 'Свиной язык', category: 'Мясо, птица', protein: 14.4, fat: 16.5, sugar: 0, calories: 203)
Ingredient.create(title: 'Телятина', category: 'Мясо, птица', protein: 19.9, fat: 1.1, sugar: 0, calories: 91)
Ingredient.create(title: 'Гуси', category: 'Мясо, птица', protein: 16.4, fat: 33.1, sugar: 0, calories: 359)
Ingredient.create(title: 'Индейка', category: 'Мясо, птица', protein: 21.1, fat: 12.3, sugar: 0.6, calories: 192)
Ingredient.create(title: 'Куры', category: 'Мясо, птица', protein: 20.4, fat: 8.6, sugar: 0.8, calories: 161)
Ingredient.create(title: 'Цыплята', category: 'Мясо, птица', protein: 18.5, fat: 7.9, sugar: 0.5, calories: 159)
Ingredient.create(title: 'Утки', category: 'Мясо, птица', protein: 16.4, fat: 61.3, sugar: 0, calories: 348)
Ingredient.create(title: 'Баклажаны', category: 'Овощи', protein: 0.6, fat: 0.1, sugar: 7.5, calories: 22)
Ingredient.create(title: 'Бобы', category: 'Овощи', protein: 6.1, fat: 0.1, sugar: 8.1, calories: 59)
Ingredient.create(title: 'Брюква', category: 'Овощи', protein: 1.2, fat: 0.1, sugar: 8.4, calories: 38)
Ingredient.create(title: 'Горошек зеленый', category: 'Овощи', protein: 5.4, fat: 0.2, sugar: 13.6, calories: 75)
Ingredient.create(title: 'Кабачки', category: 'Овощи', protein: 0.8, fat: 0.3, sugar: 5.9, calories: 30)
Ingredient.create(title: 'Капуста белокочанная', category: 'Овощи', protein: 1.9, fat: 0, sugar: 5.7, calories: 31)
Ingredient.create(title: 'Капуста краснокочанная', category: 'Овощи', protein: 1.9, fat: 0, sugar: 6.3, calories: 34)
Ingredient.create(title: 'Капуста цветная', category: 'Овощи', protein: 2.7, fat: 0, sugar: 5.2, calories: 30)
Ingredient.create(title: 'Картофель вареный', category: 'Овощи', protein: 2, fat: 0.3, sugar: 16.5, calories: 80)
Ingredient.create(title: 'Картофель жареный', category: 'Овощи', protein: 2.6, fat: 9.7, sugar: 23.5, calories: 198)
Ingredient.create(title: 'Картофель молодой', category: 'Овощи', protein: 2.2, fat: 0.3, sugar: 12.5, calories: 57)
Ingredient.create(title: 'Лук зеленый (перо)', category: 'Овощи', protein: 1.4, fat: 0, sugar: 4.2, calories: 21)
Ingredient.create(title: 'Лук порей', category: 'Овощи', protein: 3.2, fat: 0, sugar: 7.1, calories: 38)
Ingredient.create(title: 'Лук репчатый', category: 'Овощи', protein: 1.6, fat: 0, sugar: 9.3, calories: 41)
Ingredient.create(title: 'Морковь', category: 'Овощи', protein: 1.3, fat: 0.1, sugar: 6.3, calories: 29)
Ingredient.create(title: 'Огурцы грунтовые', category: 'Овощи', protein: 0.7, fat: 0, sugar: 3.1, calories: 15)
Ingredient.create(title: 'Огурцы парниковые', category: 'Овощи', protein: 0.7, fat: 0, sugar: 1.6, calories: 9)
Ingredient.create(title: 'Оливки', category: 'Овощи', protein: 0.6, fat: 10.2, sugar: 6.7, calories: 111)
Ingredient.create(title: 'Перец зеленый сладкий', category: 'Овощи', protein: 1.2, fat: 0, sugar: 4.8, calories: 24)
Ingredient.create(title: 'Перец красный сладкий', category: 'Овощи', protein: 1.2, fat: 0, sugar: 5.5, calories: 26)
Ingredient.create(title: 'Петрушка (зелень)', category: 'Овощи', protein: 3.8, fat: 0, sugar: 8, calories: 45)
Ingredient.create(title: 'Петрушка (корень)', category: 'Овощи', protein: 1.6, fat: 0, sugar: 11.2, calories: 48)
Ingredient.create(title: 'Редис', category: 'Овощи', protein: 1.5, fat: 0, sugar: 4.2, calories: 22)
Ingredient.create(title: 'Редька', category: 'Овощи', protein: 1.7, fat: 0, sugar: 7.1, calories: 33)
Ingredient.create(title: 'Репа', category: 'Овощи', protein: 1.6, fat: 0, sugar: 5.8, calories: 27)
Ingredient.create(title: 'Салат', category: 'Овощи', protein: 1.6, fat: 0, sugar: 2.1, calories: 15)
Ingredient.create(title: 'Свекла', category: 'Овощи', protein: 1.7, fat: 0, sugar: 10.5, calories: 46)
Ingredient.create(title: 'Томаты (грунтовые)', category: 'Овощи', protein: 0.7, fat: 0, sugar: 4.1, calories: 19)
Ingredient.create(title: 'Томаты (парниковые)', category: 'Овощи', protein: 0.7, fat: 0, sugar: 2.6, calories: 12)
Ingredient.create(title: 'Фасоль', category: 'Овощи', protein: 4.4, fat: 0, sugar: 4.4, calories: 36)
Ingredient.create(title: 'Хрен', category: 'Овощи', protein: 2.6, fat: 0, sugar: 16.1, calories: 70)
Ingredient.create(title: 'Чеснок', category: 'Овощи', protein: 6.6, fat: 0, sugar: 21.1, calories: 103)
Ingredient.create(title: 'Шпинат', category: 'Овощи', protein: 2.5, fat: 0, sugar: 2.6, calories: 22)
Ingredient.create(title: 'Щавель', category: 'Овощи', protein: 1.6, fat: 0, sugar: 5.5, calories: 29)
Ingredient.create(title: 'Арахис', category: 'Орехи, сухофрукты', protein: 26.2, fat: 45.3, sugar: 9.9, calories: 555)
Ingredient.create(title: 'Грецкий орех', category: 'Орехи, сухофрукты', protein: 13.5, fat: 61.5, sugar: 10.6, calories: 662)
Ingredient.create(title: 'Изюм с косточкой', category: 'Орехи, сухофрукты', protein: 1.7, fat: 0, sugar: 70.7, calories: 273)
Ingredient.create(title: 'Изюм кишмиш', category: 'Орехи, сухофрукты', protein: 2.5, fat: 0, sugar: 71.4, calories: 285)
Ingredient.create(title: 'Кешью', category: 'Орехи, сухофрукты', protein: 25.8, fat: 54.3, sugar: 13.3, calories: 647)
Ingredient.create(title: 'Курага', category: 'Орехи, сухофрукты', protein: 5.7, fat: 0, sugar: 65.3, calories: 270)
Ingredient.create(title: 'Миндаль', category: 'Орехи, сухофрукты', protein: 18.3, fat: 57.9, sugar: 13.4, calories: 643)
Ingredient.create(title: 'Семя подсолнечника', category: 'Орехи, сухофрукты', protein: 20.9, fat: 52.5, sugar: 5.4, calories: 582)
Ingredient.create(title: 'Урюк', category: 'Орехи, сухофрукты', protein: 5.3, fat: 0, sugar: 67.9, calories: 279)
Ingredient.create(title: 'Финики', category: 'Орехи, сухофрукты', protein: 2.5, fat: 0.4, sugar: 69.6, calories: 277)
Ingredient.create(title: 'Фисташки', category: 'Орехи, сухофрукты', protein: 20, fat: 50.5, sugar: 7.3, calories: 555)
Ingredient.create(title: 'Фундук', category: 'Орехи, сухофрукты', protein: 16.3, fat: 66.7, sugar: 9.8, calories: 701)
Ingredient.create(title: 'Чернослив', category: 'Орехи, сухофрукты', protein: 2.7, fat: 0, sugar: 65.3, calories: 262)
Ingredient.create(title: 'Яблоки сушенные', category: 'Орехи, сухофрукты', protein: 3.1, fat: 0, sugar: 68.3, calories: 275)
Ingredient.create(title: 'Бычки', category: 'Рыба и морепродукты', protein: 12.7, fat: 8.2, sugar: 5.1, calories: 147)
Ingredient.create(title: 'Горбуша', category: 'Рыба и морепродукты', protein: 21.2, fat: 7.1, sugar: 0, calories: 151)
Ingredient.create(title: 'Кальмар', category: 'Рыба и морепродукты', protein: 18.2, fat: 0.2, sugar: 0, calories: 77)
Ingredient.create(title: 'Камбала', category: 'Рыба и морепродукты', protein: 16, fat: 2.5, sugar: 0, calories: 86)
Ingredient.create(title: 'Карась', category: 'Рыба и морепродукты', protein: 17.5, fat: 1.6, sugar: 0, calories: 84)
Ingredient.create(title: 'Карп', category: 'Рыба и морепродукты', protein: 16, fat: 3.5, sugar: 0, calories: 95)
Ingredient.create(title: 'Кета', category: 'Рыба и морепродукты', protein: 22.1, fat: 5.8, sugar: 0, calories: 138)
Ingredient.create(title: 'Килька', category: 'Рыба и морепродукты', protein: 14.3, fat: 9.2, sugar: 0, calories: 142)
Ingredient.create(title: 'Корюшка', category: 'Рыба и морепродукты', protein: 15.3, fat: 3.3, sugar: 0, calories: 93)
Ingredient.create(title: 'Крабовое мясо', category: 'Рыба и морепродукты', protein: 16, fat: 0.9, sugar: 0, calories: 67)
Ingredient.create(title: 'Крабовые палочки', category: 'Рыба и морепродукты', protein: 17.9, fat: 2.1, sugar: 0, calories: 73)
Ingredient.create(title: 'Красноперка', category: 'Рыба и морепродукты', protein: 18.5, fat: 3.1, sugar: 0, calories: 106)
Ingredient.create(title: 'Креветка', category: 'Рыба и морепродукты', protein: 18, fat: 0.9, sugar: 0, calories: 85)
Ingredient.create(title: 'Ледяная', category: 'Рыба и морепродукты', protein: 15.6, fat: 1.3, sugar: 0, calories: 76)
Ingredient.create(title: 'Лещ', category: 'Рыба и морепродукты', protein: 17.2, fat: 4.2, sugar: 0, calories: 109)
Ingredient.create(title: 'Лосось', category: 'Рыба и морепродукты', protein: 19.2, fat: 13.8, sugar: 0, calories: 200)
Ingredient.create(title: 'Макрель', category: 'Рыба и морепродукты', protein: 20.2, fat: 3.6, sugar: 0, calories: 111)
Ingredient.create(title: 'Мидии отварные', category: 'Рыба и морепродукты', protein: 9.7, fat: 1.6, sugar: 0, calories: 53)
Ingredient.create(title: 'Минтай', category: 'Рыба и морепродукты', protein: 15.7, fat: 0.6, sugar: 0, calories: 67)
Ingredient.create(title: 'Мойва', category: 'Рыба и морепродукты', protein: 13.1, fat: 11.7, sugar: 0, calories: 159)
Ingredient.create(title: 'Навага', category: 'Рыба и морепродукты', protein: 16.71, fat: 1.3, sugar: 0, calories: 78)
Ingredient.create(title: 'Налим', category: 'Рыба и морепродукты', protein: 18.6, fat: 0.8, sugar: 0, calories: 85)
Ingredient.create(title: 'Окунь морской', category: 'Рыба и морепродукты', protein: 17.4, fat: 5.5, sugar: 0, calories: 123)
Ingredient.create(title: 'Окунь речной', category: 'Рыба и морепродукты', protein: 18.3, fat: 0.7, sugar: 0, calories: 80)
Ingredient.create(title: 'Осетр', category: 'Рыба и морепродукты', protein: 16.5, fat: 10.5, sugar: 0, calories: 161)
Ingredient.create(title: 'Осьминог', category: 'Рыба и морепродукты', protein: 18.5, fat: 0, sugar: 0, calories: 74)
Ingredient.create(title: 'Палтус', category: 'Рыба и морепродукты', protein: 18.5, fat: 3.2, sugar: 0, calories: 106)
Ingredient.create(title: 'Плотва', category: 'Рыба и морепродукты', protein: 18.5, fat: 0.4, sugar: 0, calories: 108)
Ingredient.create(title: 'Раки вареные', category: 'Рыба и морепродукты', protein: 20.3, fat: 1.2, sugar: 1.1, calories: 96)
Ingredient.create(title: 'Сазан', category: 'Рыба и морепродукты', protein: 18.1, fat: 5.2, sugar: 0, calories: 119)
Ingredient.create(title: 'Сайра', category: 'Рыба и морепродукты', protein: 18.3, fat: 20.5, sugar: 0, calories: 257)
Ingredient.create(title: 'Салака', category: 'Рыба и морепродукты', protein: 17.1, fat: 5.8, sugar: 0, calories: 124)
Ingredient.create(title: 'Сельдь', category: 'Рыба и морепродукты', protein: 17.3, fat: 19.9, sugar: 0, calories: 248)
Ingredient.create(title: 'Семга', category: 'Рыба и морепродукты', protein: 20.9, fat: 15.3, sugar: 0, calories: 222)
Ingredient.create(title: 'Сиг', category: 'Рыба и морепродукты', protein: 19, fat: 7.3, sugar: 0, calories: 141)
Ingredient.create(title: 'Скумбрия', category: 'Рыба и морепродукты', protein: 18, fat: 9.5, sugar: 0, calories: 158)
Ingredient.create(title: 'Сом', category: 'Рыба и морепродукты', protein: 16.7, fat: 8.4, sugar: 0, calories: 141)
Ingredient.create(title: 'Ставрида', category: 'Рыба и морепродукты', protein: 18, fat: 5.3, sugar: 0, calories: 119)
Ingredient.create(title: 'Стерлядь', category: 'Рыба и морепродукты', protein: 17.3, fat: 6.3, sugar: 0, calories: 126)
Ingredient.create(title: 'Судак', category: 'Рыба и морепродукты', protein: 19, fat: 0.7, sugar: 0, calories: 81)
Ingredient.create(title: 'Треска', category: 'Рыба и морепродукты', protein: 17.7, fat: 0.5, sugar: 0, calories: 76)
Ingredient.create(title: 'Тунец', category: 'Рыба и морепродукты', protein: 21.7, fat: 1.3, sugar: 0, calories: 95)
Ingredient.create(title: 'Угольная рыба', category: 'Рыба и морепродукты', protein: 13.3, fat: 11.4, sugar: 0, calories: 153)
Ingredient.create(title: 'Угорь морской', category: 'Рыба и морепродукты', protein: 14.2, fat: 30.7, sugar: 0, calories: 331)
Ingredient.create(title: 'Устрицы', category: 'Рыба и морепродукты', protein: 14.4, fat: 0.3, sugar: 6.2, calories: 91)
Ingredient.create(title: 'Форель', category: 'Рыба и морепродукты', protein: 19.6, fat: 2.1, sugar: 0, calories: 99)
Ingredient.create(title: 'Хек', category: 'Рыба и морепродукты', protein: 16.4, fat: 2.3, sugar: 0, calories: 84)
Ingredient.create(title: 'Щука', category: 'Рыба и морепродукты', protein: 18.2, fat: 0.8, sugar: 0, calories: 83)
Ingredient.create(title: 'Язык морской', category: 'Рыба и морепродукты', protein: 10.3, fat: 5.3, sugar: 0, calories: 89)
Ingredient.create(title: 'Варенье', category: 'Сладости', protein: 0.4, fat: 0.2, sugar: 74.5, calories: 286)
Ingredient.create(title: 'Вафли', category: 'Сладости', protein: 8.2, fat: 19.8, sugar: 53.1, calories: 425)
Ingredient.create(title: 'Гематоген', category: 'Сладости', protein: 6.2, fat: 2.8, sugar: 75.5, calories: 352)
Ingredient.create(title: 'Драже фруктовое', category: 'Сладости', protein: 3.7, fat: 10.3, sugar: 73.4, calories: 388)
Ingredient.create(title: 'Зефир', category: 'Сладости', protein: 0.7, fat: 0, sugar: 77.3, calories: 295)
Ingredient.create(title: 'Ирис', category: 'Сладости', protein: 3.1, fat: 7.7, sugar: 81.2, calories: 384)
Ingredient.create(title: 'Карамель', category: 'Сладости', protein: 0, fat: 0.2, sugar: 77.3, calories: 291)
Ingredient.create(title: 'Конфеты шоколадные', category: 'Сладости', protein: 3.9, fat: 39.7, sugar: 54.6, calories: 576)
Ingredient.create(title: 'Мармелад', category: 'Сладости', protein: 0, fat: 0.2, sugar: 77.1, calories: 289)
Ingredient.create(title: 'Мед', category: 'Сладости', protein: 0.6, fat: 0, sugar: 80.5, calories: 312)
Ingredient.create(title: 'Мороженое пломбир', category: 'Сладости', protein: 3.6, fat: 15.1, sugar: 20.5, calories: 223)
Ingredient.create(title: 'Мороженое сливочное', category: 'Сладости', protein: 3.6, fat: 10, sugar: 19.5, calories: 182)
Ingredient.create(title: 'Мороженое эскимо', category: 'Сладости', protein: 3.6, fat: 20, sugar: 19.5, calories: 278)
Ingredient.create(title: 'Пастила', category: 'Сладости', protein: 0.6, fat: 0, sugar: 80.1, calories: 301)
Ingredient.create(title: 'Печенье овсяное', category: 'Сладости', protein: 6.5, fat: 14.1, sugar: 71.4, calories: 430)
Ingredient.create(title: 'Печенье сдобное', category: 'Сладости', protein: 10.5, fat: 5.2, sugar: 76, calories: 447)
Ingredient.create(title: 'Пирожное слоеное', category: 'Сладости', protein: 5.7, fat: 38.3, sugar: 46.8, calories: 543)
Ingredient.create(title: 'Пирожное бисквитное', category: 'Сладости', protein: 4.9, fat: 9.1, sugar: 84.1, calories: 338)
Ingredient.create(title: 'Пряники', category: 'Сладости', protein: 4.4, fat: 2.9, sugar: 77.1, calories: 333)
Ingredient.create(title: 'Сахар', category: 'Сладости', protein: 0.2, fat: 0, sugar: 99.6, calories: 377)
Ingredient.create(title: 'Халва подсолнечная', category: 'Сладости', protein: 11.4, fat: 29.3, sugar: 54.6, calories: 519)
Ingredient.create(title: 'Шоколад темный', category: 'Сладости', protein: 5.2, fat: 35.6, sugar: 52.4, calories: 546)
Ingredient.create(title: 'Шоколад молочный', category: 'Сладости', protein: 6.7, fat: 35.6, sugar: 52.4, calories: 552)
Ingredient.create(title: 'Абрикосы', category: 'Фрукты и ягоды', protein: 0.7, fat: 0, sugar: 10.1, calories: 44)
Ingredient.create(title: 'Айва', category: 'Фрукты и ягоды', protein: 0.6, fat: 0, sugar: 8.7, calories: 37)
Ingredient.create(title: 'Алыча', category: 'Фрукты и ягоды', protein: 0.3, fat: 0, sugar: 7.6, calories: 35)
Ingredient.create(title: 'Ананас', category: 'Фрукты и ягоды', protein: 0.3, fat: 0, sugar: 11.9, calories: 49)
Ingredient.create(title: 'Апельсин', category: 'Фрукты и ягоды', protein: 0.8, fat: 0, sugar: 8.6, calories: 38)
Ingredient.create(title: 'Бананы', category: 'Фрукты и ягоды', protein: 1.7, fat: 0, sugar: 22.1, calories: 87)
Ingredient.create(title: 'Брусника', category: 'Фрукты и ягоды', protein: 0.6, fat: 0, sugar: 8.8, calories: 42)
Ingredient.create(title: 'Виноград', category: 'Фрукты и ягоды', protein: 0.5, fat: 0, sugar: 17.8, calories: 73)
Ingredient.create(title: 'Вишня', category: 'Фрукты и ягоды', protein: 0.9, fat: 0, sugar: 11.1, calories: 46)
Ingredient.create(title: 'Гранат', category: 'Фрукты и ягоды', protein: 0.9, fat: 0, sugar: 11.9, calories: 53)
Ingredient.create(title: 'Грейпфрут', category: 'Фрукты и ягоды', protein: 0.8, fat: 0, sugar: 7.5, calories: 37)
Ingredient.create(title: 'Груша', category: 'Фрукты и ягоды', protein: 0.5, fat: 0, sugar: 10.6, calories: 41)
Ingredient.create(title: 'Голубика', category: 'Фрукты и ягоды', protein: 1.1, fat: 0, sugar: 7.4, calories: 35)
Ingredient.create(title: 'Дыня', category: 'Фрукты и ягоды', protein: 0.8, fat: 0.3, sugar: 7.3, calories: 34)
Ingredient.create(title: 'Ежевика', category: 'Фрукты и ягоды', protein: 1.9, fat: 0, sugar: 5.1, calories: 31)
Ingredient.create(title: 'Земляника', category: 'Фрукты и ягоды', protein: 1.9, fat: 0, sugar: 7.1, calories: 40)
Ingredient.create(title: 'Инжир', category: 'Фрукты и ягоды', protein: 0.9, fat: 0, sugar: 13.7, calories: 57)
Ingredient.create(title: 'Киви', category: 'Фрукты и ягоды', protein: 1, fat: 0.7, sugar: 9.7, calories: 46)
Ingredient.create(title: 'Кизил', category: 'Фрукты и ягоды', protein: 1.1, fat: 0, sugar: 9.4, calories: 42)
Ingredient.create(title: 'Клубника', category: 'Фрукты и ягоды', protein: 0.6, fat: 0.4, sugar: 7, calories: 30)
Ingredient.create(title: 'Клюква', category: 'Фрукты и ягоды', protein: 0.7, fat: 0, sugar: 4.9, calories: 27)
Ingredient.create(title: 'Крыжовник', category: 'Фрукты и ягоды', protein: 0.8, fat: 0, sugar: 9.7, calories: 43)
Ingredient.create(title: 'Лимон', category: 'Фрукты и ягоды', protein: 0.9, fat: 0, sugar: 3.3, calories: 30)
Ingredient.create(title: 'Малина', category: 'Фрукты и ягоды', protein: 0.7, fat: 0, sugar: 9.2, calories: 43)
Ingredient.create(title: 'Мандарин', category: 'Фрукты и ягоды', protein: 0.9, fat: 0, sugar: 8.8, calories: 39)
Ingredient.create(title: 'Манго', category: 'Фрукты и ягоды', protein: 0.6, fat: 0.4, sugar: 11.8, calories: 69)
Ingredient.create(title: 'Морошка', category: 'Фрукты и ягоды', protein: 0.9, fat: 0, sugar: 6.9, calories: 33)
Ingredient.create(title: 'Облепиха', category: 'Фрукты и ягоды', protein: 0.8, fat: 0, sugar: 5.6, calories: 31)
Ingredient.create(title: 'Персики', category: 'Фрукты и ягоды', protein: 0.9, fat: 0, sugar: 10.1, calories: 42)
Ingredient.create(title: 'Памело', category: 'Фрукты и ягоды', protein: 0.6, fat: 0.1, sugar: 6.1, calories: 29)
Ingredient.create(title: 'Рябина', category: 'Фрукты и ягоды', protein: 1.6, fat: 0, sugar: 12.2, calories: 57)
Ingredient.create(title: 'Слива', category: 'Фрукты и ягоды', protein: 0.8, fat: 0, sugar: 9.7, calories: 41)
Ingredient.create(title: 'Смородина белая', category: 'Фрукты и ягоды', protein: 0.4, fat: 0, sugar: 8.5, calories: 37)
Ingredient.create(title: 'Смородина красная', category: 'Фрукты и ягоды', protein: 0.6, fat: 0, sugar: 8.7, calories: 39)
Ingredient.create(title: 'Смородина черная', category: 'Фрукты и ягоды', protein: 1.0, fat: 0, sugar: 8.0, calories: 38)
Ingredient.create(title: 'Хурма', category: 'Фрукты и ягоды', protein: 0.7, fat: 0, sugar: 15.7, calories: 61)
Ingredient.create(title: 'Черешня', category: 'Фрукты и ягоды', protein: 1.3, fat: 0, sugar: 12.5, calories: 54)
Ingredient.create(title: 'Черника', category: 'Фрукты и ягоды', protein: 1.2, fat: 0, sugar: 8.8, calories: 41)
Ingredient.create(title: 'Шелковица', category: 'Фрукты и ягоды', protein: 0.6, fat: 0, sugar: 12.5, calories: 50)
Ingredient.create(title: 'Шиповник свежий', category: 'Фрукты и ягоды', protein: 1.5, fat: 0, sugar: 24.2, calories: 106)
Ingredient.create(title: 'Шиповник сушеный', category: 'Фрукты и ягоды', protein: 4.5, fat: 0, sugar: 60.1, calories: 259)
Ingredient.create(title: 'Яблоки', category: 'Фрукты и ягоды', protein: 0.5, fat: 0, sugar: 11.4, calories: 48)
Ingredient.create(title: 'Баранки', category: 'Хлеб и хлебобулочные изделия, мука', protein: 16.4, fat: 1.1, sugar: 69.7, calories: 342)
Ingredient.create(title: 'Батон нарезной', category: 'Хлеб и хлебобулочные изделия, мука', protein: 9.4, fat: 2.7, sugar: 50.7, calories: 261)
Ingredient.create(title: 'Бублики', category: 'Хлеб и хлебобулочные изделия, мука', protein: 16.4, fat: 1.1, sugar: 69.7, calories: 342)
Ingredient.create(title: 'Булочка', category: 'Хлеб и хлебобулочные изделия, мука', protein: 7.4, fat: 1.8, sugar: 43.7, calories: 218)
Ingredient.create(title: 'Лаваш армянский', category: 'Хлеб и хлебобулочные изделия, мука', protein: 7.7, fat: 1.1, sugar: 47.8, calories: 239)
Ingredient.create(title: 'Мука пшеничная высшего сорта', category: 'Хлеб и хлебобулочные изделия, мука', protein: 10.4, fat: 0.8, sugar: 74.5, calories: 324)
Ingredient.create(title: 'Мука пшеничная I сорта', category: 'Хлеб и хлебобулочные изделия, мука', protein: 10.6, fat: 1.4, sugar: 73.6, calories: 329)
Ingredient.create(title: 'Мука пшеничная II сорта', category: 'Хлеб и хлебобулочные изделия, мука', protein: 11.6, fat: 1.9, sugar: 70.7, calories: 328)
Ingredient.create(title: 'Мука ржаная', category: 'Хлеб и хлебобулочные изделия, мука', protein: 6.8, fat: 1.2, sugar: 76.8, calories: 321)
Ingredient.create(title: 'Сушки', category: 'Хлеб и хлебобулочные изделия, мука', protein: 11.1, fat: 1, sugar: 73.2, calories: 335)
Ingredient.create(title: 'Сухари пшеничные', category: 'Хлеб и хлебобулочные изделия, мука', protein: 11.6, fat: 1.8, sugar: 72.1, calories: 327)
Ingredient.create(title: 'Хлеб ржаной', category: 'Хлеб и хлебобулочные изделия, мука', protein: 4.7, fat: 0.6, sugar: 49.5, calories: 210)
Ingredient.create(title: 'Хлеб пшеничный из муки I сорта', category: 'Хлеб и хлебобулочные изделия, мука', protein: 7.4, fat: 2.2, sugar: 53, calories: 246)
Ingredient.create(title: 'Омлет', category: 'Яйца', protein: 9.7, fat: 15.5, sugar: 1.7, calories: 181)
Ingredient.create(title: 'Яйцо куриное', category: 'Яйца', protein: 12.7, fat: 11.1, sugar: 0.6, calories: 153)
Ingredient.create(title: 'Яйцо перепелиное', category: 'Яйца', protein: 11.9, fat: 13.3, sugar: 0.8, calories: 170)
Ingredient.create(title: 'Яйцо страусиное', category: 'Яйца', protein: 12.4, fat: 11.5, sugar: 0.8, calories: 118)
Ingredient.create(title: 'Яйцо утиное', category: 'Яйца', protein: 13.5, fat: 14.1, sugar: 0.2, calories: 176)
Ingredient.create(title: 'Яичный порошок', category: 'Яйца', protein: 45.3, fat: 37.3, sugar: 5.1, calories: 545)

p "Removing existing #{Role.all.count} roles"
Role.destroy_all
p "Creating 3 roles"
[:newuser, :admin, :editor].each do |role|
  Role.create(name: role)
end
p "Should have created 3 Roles, roles created: #{Role.all.count}"